#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Smarthome_Mobile.Client.HD.Resource", IsApplication=true)]

namespace Smarthome_Mobile.Client.HD
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int i1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001a
			public const int btnLogin = 2131034138;
			
			// aapt resource value: 0x7f050015
			public const int lab1 = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int lab2 = 2131034135;
			
			// aapt resource value: 0x7f050007
			public const int labHumidity = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int labLight = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int labSmoke = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int labSysState = 2131034131;
			
			// aapt resource value: 0x7f050003
			public const int labTemp1 = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int linear1 = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int linear2 = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int linear3 = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int linear4 = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int linear5 = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int progressBarHumidity = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int progressBarLight = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int progressBarTemp = 2131034116;
			
			// aapt resource value: 0x7f050014
			public const int root1 = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int switch1 = 2131034130;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int textView2 = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int textView3 = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int textView4 = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int textView5 = 2131034129;
			
			// aapt resource value: 0x7f050019
			public const int txtAddress = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int txtPassword = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int txtUsername = 2131034134;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dashboard = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
